import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'screens/home_screen.dart';
import 'screens/login_screen.dart';
import 'services/auth_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    // firebase_options.dart will be generated by FlutterFire CLI (see README)
  );
  runApp(const SellMyAppApp());
}

class SellMyAppApp extends StatelessWidget {
  const SellMyAppApp({super.key});

  @override
  Widget build(BuildContext context) {
    const brandRed = Color(0xFFB50101);
    return MaterialApp(
      title: 'SellMyApp',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorSchemeSeed: brandRed,
        useMaterial3: true,
        fontFamily: 'Roboto',
        // Material 3 auto-generates a muted/pastel tonal palette from the
        // seed color for containers, buttons, chips, etc. That looks washed
        // out next to our logo, so force the vivid brand red directly on
        // the widgets that show it most (buttons, selected chips, FAB).
        colorScheme: ColorScheme.fromSeed(
          seedColor: brandRed,
          brightness: Brightness.light,
        ).copyWith(
          primary: brandRed,
          onPrimary: Colors.white,
          secondary: brandRed,
          onSecondary: Colors.white,
        ),
        filledButtonTheme: FilledButtonThemeData(
          style: FilledButton.styleFrom(
            backgroundColor: brandRed,
            foregroundColor: Colors.white,
          ),
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: brandRed,
            foregroundColor: Colors.white,
          ),
        ),
        chipTheme: ChipThemeData(
          selectedColor: brandRed,
          secondarySelectedColor: brandRed,
          labelStyle: const TextStyle(color: Colors.black87),
          side: BorderSide(color: Colors.grey.shade400),
        ),
        floatingActionButtonTheme: const FloatingActionButtonThemeData(
          backgroundColor: brandRed,
          foregroundColor: Colors.white,
        ),
        outlinedButtonTheme: OutlinedButtonThemeData(
          style: OutlinedButton.styleFrom(
            foregroundColor: brandRed,
            side: const BorderSide(color: brandRed),
          ),
        ),
        textButtonTheme: TextButtonThemeData(
          style: TextButton.styleFrom(foregroundColor: brandRed),
        ),
        appBarTheme: AppBarTheme(
          backgroundColor: brandRed,
          foregroundColor: Colors.white,
          elevation: 0,
          iconTheme: const IconThemeData(color: Colors.white),
          titleTextStyle: const TextStyle(
            color: Colors.white,
            fontSize: 20,
            fontWeight: FontWeight.w600,
          ),
        ),
        scaffoldBackgroundColor: Colors.white,
      ),
      home: const AuthGate(),
    );
  }
}

// Shows Home if logged in, Login screen if not
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder(
      stream: AuthService().authStateChanges,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }
        if (snapshot.hasData) {
          return const HomeScreen();
        }
        return const LoginScreen();
      },
    );
  }
}
